x-redis-cluster: &x-redis-cluster
    image: redis:alpine
    volumes:
      - ./:/work
    command:
      - /bin/sh
      - -c
      - |
        rm -f /tmp/redis-cluster-nodes.conf
        redis-server /work/redis-cluster_${REDIS_CLUSTER_ID}.conf

services:
  redis-cluster_0:
    <<: *x-redis-cluster
    environment:
      - REDIS_CLUSTER_ID=0
    ports:
      - "6380:6380"

  redis-cluster_1:
    ports:
      - "6381:6381"
    environment:
      - REDIS_CLUSTER_ID=1
