x-redis-cluster: &x-redis-cluster
  image: redis:alpine
  network_mode: host
  volumes:
    - ./:/work
  working_dir: /work
  environment:
    - REDIS_CLUSTER_CONFIG_FILE=${REDIS_CLUSTER_CONFIG_FILE:-/tmp/nodes.conf}
    - REDIS_PORT=${REDIS_PORT:-6379}
  entrypoint: /bin/sh
  command:
    - -c
    - |
      rm -f $$REDIS_CLUSTER_CONFIG_FILE && \
      redis-server --port $$REDIS_PORT --appendonly no --save "" --cluster-enabled yes --cluster-config-file $$REDIS_CLUSTER_CONFIG_FILE
  healthcheck:
    test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
    interval: 10s
    timeout: 5s
    retries: 5

services:
  redis-cluster_0:
    <<: *x-redis-cluster
    environment:
      - REDIS_PORT=36380

  redis-cluster_1:
    <<: *x-redis-cluster
    environment:
      - REDIS_PORT=36381

  redis-cluster_2:
    <<: *x-redis-cluster
    environment:
      - REDIS_PORT=36382
