x-redis-cluster: &x-redis-cluster
  image: redis:alpine
  volumes:
    - ./:/work
  working_dir: /work
  command:
    - /bin/sh
    - -c
    - |
      rm -f /tmp/redis-cluster-nodes.conf
      redis-server redis.conf
  healthcheck:
    test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
    interval: 10s
    timeout: 5s
    retries: 5

services:
  redis-cluster_0:
    <<: *x-redis-cluster
    ports:
      - "127.0.0.1:6380:6379"

  redis-cluster_1:
    <<: *x-redis-cluster
    ports:
      - "127.0.0.1:6381:6379"
