[build-system]
build-backend = "hatchling.build"
requires = ["hatchling", "hatch-vcs"]

[project]
authors = [{name = "Liu Xue Yan", email = "liu_xue_yan@foxmail.com"}]
description = "A Python library that provides decorators for caching function results in Redis, supporting multiple serialization formats and caching strategies, as well as asynchronous operations."
name = "redis_func_cache"
readme = "README.md"

requires-python = ">=3.10"

keywords = ["redis", "cache", "decorator"]

license = "BSD-3-Clause"
license-files = ["LICENSE.md"]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Lua",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: System :: Distributed Computing",
  "Typing :: Typed",
]

dynamic = ["version"]

dependencies = [
  "redis>=5.2,<9",
  "typing-extensions>=4.5.0; python_version<'3.12'",
]

[project.urls]
changelog = "https://github.com/tanbro/redis_func_cache/main/CHANGELOG.md"
documentation = "https://redis-func-cache.readthedocs.io/"
homepage = "https://github.com/tanbro/redis_func_cache"
issues = "https://github.com/tanbro/redis_func_cache/issues"
source = "https://github.com/tanbro/redis_func_cache.git"

[project.optional-dependencies]
all = [
  "redis[hiredis]",
  "Pygments>=2.9",
  "dill>=0.3.6",
  "pymongo>=3.9",
  "msgpack>=1.0",
  "PyYAML>=5.4",
  "cbor2>=5.0",
  "cloudpickle>=3.0",
]
bson = ["pymongo>=3.9"]
cbor = ["cbor2>=5.0"]
cloudpickle = ["cloudpickle>=3.0"]
dill = ["dill>=0.3.6"]
hiredis = ["redis[hiredis]"]
msgpack = ["msgpack>=1.0"]
pygments = ["Pygments>=2.9"]
yaml = ["PyYAML>=5.4"]

[dependency-groups]
dev = [
  {include-group = "typing"},
  {include-group = "test"},
  {include-group = "docs"},
]
docs = [
  "importlib_metadata;python_version<'3.8'",
  "Sphinx>=7",
  "myst-parser",
  "sphinx-book-theme",
  "sphinxcontrib-mermaid",
  "linkify-it-py",
  "sphinx-copybutton",
  "sphinx-inline-tabs",
  "sphinx_tippy",
  "sphinx-version-warning",
  "sphinx-autodoc-typehints",
]
test = [
  "pytest",
  "pytest-mock",
  "pytest-cov",
  "pytest-asyncio",
  "python-dotenv",
]
typing = ["mypy"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/redis_func_cache/_version.py"
