"""Golden contract tests pinning the observable behavior of every built-in policy.

The fixture ``tests/_golden.json`` is generated by ``tests/_gen_golden.py`` and
freezes the version-independent parts of the on-the-wire contract:

- the Redis key pair each policy produces for two distinct functions
  (the function checksum, which embeds bytecode and therefore differs across
  Python versions, is templated as ``{checksum_a}`` / ``{checksum_b}``),
- the extra ARGV entries (``calc_ext_args``),
- the (get, put) Lua script file names.

The sub-key digest is not frozen (it also embeds bytecode); ``test_hash``
recomputes it independently from the documented fingerprint recipe instead.
"""

from __future__ import annotations

import hashlib
import json
import pickle
from pathlib import Path
from typing import Any, cast

import pytest

from redis_func_cache import RedisFuncCache
from redis_func_cache.fingerprint import hash_fingerprint
from redis_func_cache.policies import Policy
from redis_func_cache.scripts import Script
from redis_func_cache.utils import b64digest, calculate_callable_fullname, get_callable_bytecode

from ._golden_fns import fn_a, fn_b

CHECKSUM_A = b64digest(hash_fingerprint("md5", True, fn_a)).decode()
CHECKSUM_B = b64digest(hash_fingerprint("md5", True, fn_b)).decode()

GOLDEN = json.loads((Path(__file__).with_name("_golden.json")).read_text(encoding="utf-8"))

PREFIX, NAME = "gp:", "gn"
ARGS, KWDS = (1,), {"x": "a"}


def _policies() -> list[tuple[str, Policy]]:
    """Collect every built-in policy preset bound to the golden namespace."""
    import redis_func_cache.policies.fifo as fifo_mod
    import redis_func_cache.policies.lfu as lfu_mod
    import redis_func_cache.policies.lru as lru_mod
    import redis_func_cache.policies.mru as mru_mod
    import redis_func_cache.policies.rr as rr_mod

    out: list[tuple[str, Policy]] = []
    for module in (fifo_mod, lfu_mod, lru_mod, mru_mod, rr_mod):
        for attr in dir(module):
            policy = getattr(module, attr)
            if isinstance(policy, Policy):
                policy._bind(PREFIX, NAME)
                out.append((attr, policy))
    assert len(out) == len(GOLDEN)
    return out


class _RecordScript:
    """Stands in for a registered redis Script, recording keys and args."""

    def __init__(self, calls: list[dict[str, Any]]) -> None:
        self._calls = calls

    def __call__(self, keys=None, args=None, client=None):
        assert keys is not None
        assert args is not None
        self._calls.append({"keys": list(keys), "args": list(args)})


class _RecordingClient:
    def __init__(self, calls: list[dict[str, Any]]) -> None:
        self._calls = calls

    def register_script(self, script):
        return _RecordScript(self._calls)


@pytest.mark.parametrize("policy", _policies(), ids=lambda p: p[0])
class TestGoldenPolicyContract:
    def test_keys(self, policy):
        name, policy = policy
        expected = GOLDEN[name]
        keys_a = [k.replace("{checksum_a}", CHECKSUM_A).replace("{checksum_b}", CHECKSUM_B) for k in expected["keys_a"]]
        keys_b = [k.replace("{checksum_a}", CHECKSUM_A).replace("{checksum_b}", CHECKSUM_B) for k in expected["keys_b"]]
        assert list(policy.calc_key_pair(fn_a, ARGS, KWDS)) == keys_a
        assert list(policy.calc_key_pair(fn_b, ARGS, KWDS)) == keys_b

    def test_hash(self, policy):
        """The digest must equal md5(fullname + bytecode + pickle(args) + pickle(kwds)).

        Recomputed independently of the library implementation; the bytecode
        input legitimately differs across Python versions, so no frozen hex
        can be pinned here.
        """
        _, policy = policy
        h = hashlib.md5()
        h.update(calculate_callable_fullname(fn_a).encode())
        h.update(get_callable_bytecode(fn_a))
        h.update(pickle.dumps(ARGS))
        h.update(pickle.dumps(KWDS))
        hash_value = policy.calc_hash(fn_a, ARGS, KWDS)
        assert isinstance(hash_value, bytes)  # every built-in hasher returns raw digest bytes
        assert hash_value == h.digest()

    def test_ext_args(self, policy):
        name, policy = policy
        assert list(policy.calc_ext_args(fn_a, ARGS, KWDS) or ()) == GOLDEN[name]["ext_args"]

    def test_scripts(self, policy):
        name, policy = policy
        assert [policy.scripts.get_script, policy.scripts.put_script] == GOLDEN[name]["scripts"]


class TestGoldenArgvLayout:
    """Pin the ARGV layout of get/put: ext_args must land on ARGV[7] of put,
    the reserved options JSON goes last."""

    def test_put_argv(self):
        calls: list[dict[str, Any]] = []  # type: ignore[annotation-unchecked]
        RedisFuncCache.put(
            cast(Script, _RecordScript(calls)),
            keys=("z", "h"),
            hash_value=b"deadbeef",
            value="v",
            maxsize=10,
            update_ttl=True,
            ttl=60,
            field_ttl=30,
            ext_args=("mru",),
        )
        assert calls == [
            {
                "keys": ["z", "h"],
                "args": [10, 1, 60, b"deadbeef", "v", 30, "mru", b"{}"],
            }
        ]

    def test_put_argv_no_ext_args_options_last(self):
        calls: list[dict[str, Any]] = []  # type: ignore[annotation-unchecked]
        RedisFuncCache.put(
            cast(Script, _RecordScript(calls)),
            keys=("z", "h"),
            hash_value=b"deadbeef",
            value="v",
            maxsize=10,
            update_ttl=False,
            ttl=0,
        )
        assert calls[0]["args"] == [10, 0, 0, b"deadbeef", "v", 0, b"{}"]

    def test_get_argv(self):
        calls: list[dict[str, Any]] = []  # type: ignore[annotation-unchecked]
        RedisFuncCache.get(
            cast(Script, _RecordScript(calls)),
            keys=("z", "h"),
            hash_value=b"deadbeef",
            update_ttl=True,
            ttl=60,
            options={"a": 1},
            ext_args=("mru",),
        )
        assert calls[0]["args"][:4] == [1, 60, b"deadbeef", json.dumps({"a": 1}, separators=(",", ":")).encode()]
        assert calls[0]["args"][4:] == ["mru"]

    def test_policy_ext_args_land_on_argv7(self):
        """End-to-end: a policy's ext_args flow into put's ARGV[7]."""
        calls: list[dict[str, Any]] = []  # type: ignore[annotation-unchecked]
        client = _RecordingClient(calls)
        scripts = tuple(client.register_script(t) for t in ("get", "put"))
        name, policy = _policies()[0]
        keys, hash_value, ext_args = (
            policy.calc_key_pair(fn_a, ARGS, KWDS),
            policy.calc_hash(fn_a, ARGS, KWDS),
            policy.calc_ext_args(fn_a, ARGS, KWDS) or (),
        )
        RedisFuncCache.put(
            cast(Script, scripts[1]), keys, hash_value, "v", maxsize=10, update_ttl=True, ttl=60, ext_args=ext_args
        )
        expected_ext = GOLDEN[name]["ext_args"]
        args = calls[0]["args"]
        assert list(args[6 : 6 + len(expected_ext)]) == expected_ext
        assert args[-1] == b"{}"
