name: redis_func_cache

include:
  - docker-compose.redis.yml

services:
  unittest:
    image: quay.io/pypa/manylinux_2_28_x86_64
    network_mode: host
    depends_on:
      redis-standalone:
        condition: service_healthy
      redis-cluster-creator:
        condition: service_healthy
    volumes:
      - type: bind
        source: ..
        target: /workspace
    working_dir: /workspace
    environment:
      PIP_INDEX_URL: ${PIP_INDEX_URL:-https://mirrors.cloud.tencent.com/pypi/simple}
      REDIS_URL: ${REDIS_URL:-redis://127.0.0.1:6379}
      REDIS_CLUSTER_NODES: ${REDIS_CLUSTER_NODES:-127.0.0.1:6380 127.0.0.1:6381 127.0.0.1:6382}
    entrypoint: bash
    command:
      - tests/run.sh
